@startsalt
title KDS - Кухооный Экран
{+
  <b>Очередь заказов (Активных: 3)
  --
  {
    {^" <b>#2045 (Зал) | 10:15 (5 мин) "
      .
      * <b>2x</b> Сдобная булка
      * <b>1x</b> Капучино
      .
      [ Готово к выдаче ]
    }
    |
    {^" <b>#2046 (С собой) | 10:17 (3 мин) "
      .
      * <b>1x</b> Круассан миндаль
      * <b>1x</b> Латте 0.4
      .
      [ Готово к выдаче ]
    }
    |
    {^" <b>#2047 (Delivery) | 10:19 (1 мин) "
      .
      * <b>5x</b> Пончик шок.
      * <b>2x</b> Чай черный
      .
      [ Готово к выдаче ]
    }
  }
  --
  [ Показать выполненные ]
}
@endsalt