@startsalt
title Мобильное приложение "Сдобная булка"
{+
  <b>Сдобная булка 🥐
  [ Поиск по меню...       ]
  ~
  {/ <b>Меню</b> | Акции | Мои заказы }
  ~
  {
      <b>Популярное
      .
      { [X] | **Сдобная булка** \n Фирменная, с корицей \n 150 ₽ | [ В корзину ] }
      ---
      { [X] | **Капучино 0.3** \n На кокосовом молоке \n 220 ₽ | [ В корзину ] }
      ---
      { [X] | **Круассан** \n С миндалем \n 180 ₽ | [ В корзину ] }
  }
  ~
  ===
  [ 🛒 Корзина: 2 товара (370 ₽) ]
}
@endsalt