@startsalt
title POS-терминал (Рабочее место баристы)
{+
  {/ <b>Прием заказа</b> | История заказов | Закрытие смены | Настройки }
  {
    {
       <b>Категории:
       [ Горячие напитки ] [ Холодные напитки ]
       [ Выпечка ] [ Десерты ] [ Сэндвичи ]
       --
       <b>Товары:
       {
          [ Эспрессо ] | [ Американо ] | [ Капучино ]
          [ Латте ]    | [ Раф ]       | [ Флэт Уайт ]
          --
          [ Сдобная булка ] | [ Круассан ] | [ Сосиска в тесте ]
          [ Ватрушка ]      | [ Донат ]    | [ Чизкейк ]
       }
    }
    |
    {
       <b>Новый заказ #2045
       Клиент: "Иван" (Тел: 999...)
       .
       {|
         Товар         | Кол-во | Сумма
         Сдобная булка | 2      | 300
         Капучино 0.3  | 1      | 220
         Сироп (Доп)   | 1      | 30
       }
       .
       <b>Итого к оплате: 550 ₽
       --
       [ 💳 Терминал ] [ 💵 Наличные ] [ 📱 QR-код ]
       [ Отложить ]   [ 🖨 Печать ]
    }
  }
}
@endsalt