@startsalt
title Прототип страницы "Портфель"
{+
    ' Навигационное меню
    {* <b>Мой Портфель</b> | Заявки | Профиль | Выход }
    
    {/ <b>Сводка</b> | Аналитика }
    
    ' Блок общей стоимости
    ^Текущая оценка портфеля^
    {
       Общая стоимость: | <b>1 250 400 RUB</b>
       Изменение за день: | <color:green>+12 500 RUB (+1.01%)</color>
    }
    
    --
    
    ' Таблица активов
    ^Список инструментов^
    {#
    <b>Тип</b> | <b>Инструмент</b> | <b>Кол-во</b> | <b>Тек. цена</b> | <b>Прибыль (Abs)</b> | <b>Прибыль (%)</b> | <b>Действия</b>
    Акция | Яндекс (YNDX) | 100 шт. | 2 500 RUB | <color:green>+15 000 RUB</color> | <color:green>+6.3%</color> | [ Продать ]
    Облигация | ОФЗ-26238 | 50 шт. | 950 RUB | <color:red>-2 500 RUB</color> | <color:red>-5.0%</color> | [ Продать ]
    Фонд | FXUS ETF | 200 шт. | 120 RUB | <color:green>+4 000 RUB</color> | <color:green>+20.0%</color> | [ Продать ]
    Акция | Сбербанк (SBER) | 1000 шт.| 260 RUB | <color:gray>0 RUB</color> | <color:gray>0.0%</color> | [ Продать ]
    }
    
    .
    [ Обновить котировки ]
}
@endsalt