@startsalt
title Прототип страницы "Заявки"
{+
    ' Навигационное меню
    {* Мой Портфель | <b>Заявки</b> | Профиль | Выход }
    
    ' Панель управления
    {
        Поиск по тикеру: | "           " | [Найти]
        .
        [ <b>+ Новая заявка (Купить/Продать)</b> ]
    }
    
    --
    
    ' Секция Активных заявок
    ^Активные заявки (В ожидании)^
    {#
    <b>Дата/Время</b> | <b>Тип</b> | <b>Инструмент</b> | <b>Кол-во</b> | <b>Цена</b> | <b>Сумма</b> | <b>Статус</b> | <b>Действие</b>
    24.10 14:30 | <color:blue>BUY</color> | Газпром (GAZP) | 100 | 160 RUB | 16 000 RUB | В работе | [Отменить]
    }
    
    .
    --
    .
    
    ' Секция Истории
    ^История операций^
    {#
    <b>Дата/Время</b> | <b>Тип</b> | <b>Инструмент</b> | <b>Кол-во</b> | <b>Цена</b> | <b>Сумма</b> | <b>Статус</b>
    23.10 10:15 | <color:red>SELL</color> | Лукойл (LKOH) | 10 | 6 500 RUB | 65 000 RUB | <b>Исполнена</b>
    22.10 18:00 | <color:blue>BUY</color> | Сбер (SBER) | 50 | 255 RUB | 12 750 RUB | <b>Исполнена</b>
    20.10 09:00 | <color:blue>BUY</color> | Яндекс (YNDX) | 5 | 2 300 RUB | 11 500 RUB | <color:gray>Отменена</color>
    }
    
    .
    {/ <b><  1  2  3  ></b> }
}
@endsalt