@startuml
start

:Инициализация данных;
note right
  Гири: {(1, 100), (2, 75), ... (7, 10)}
  Длины плеч: L1..L8
end note

:Генерация всех возможных перестановок гирь;
note right
  Все варианты порядка гирь
end note

:Генерация паттернов распределения;
note right
  Разбиение 7 гирь на 5 групп:
  две чаши по 2 гири, три по 1
  (например: 2, 2, 1, 1, 1)
end note

while (Есть следующая перестановка?) is (Да)
  
  :Заполнить чаши A, B, C, D, E гирями
  (согласно текущей перестановке и паттерну);

  if (<color:red><b>Гиря №7 в чаше D?</b></color>) then (Да)
    
    :Рассчитать суммарную массу 
    в каждой чаше (mA, mB, mC, mD, mE);

    partition "Проверка физики (равновесие)" {
      
      if (<b>Нижний правый рычаг</b>\nmC * 1 == mD * 4 ?) then (Да)
        
        if (<b>Средний правый рычаг</b>\n(mC + mD) * 1 == mE * 2 ?) then (Да)
          
          if (<b>Левый рычаг</b>\nmA * 2 == mB * 1 ?) then (Да)
            
            :Рассчитать массу левой ветви
            mLeft = mA + mB;
            :Рассчитать массу правой ветви
            mRight = mC + mD + mE;

            if (<b>Главный верхний рычаг</b>\nmLeft * 1 == mRight * 3 ?) then (Да)
               #lightgreen:<b>РЕШЕНИЕ НАЙДЕНО</b>;
               :Сформировать список пар
               (Название чаши - Номер гири);
               stop
            else (Нет)
            endif

          else (Нет)
          endif

        else (Нет)
        endif

      else (Нет)
      endif
    }

  else (Нет)
    note right
      Условие задачи:
      самая легкая гиря
      должна быть в D
    end note
  endif

endwhile (Нет)

:Решение не найдено;
stop

@enduml